'use client';
import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navbar
    nav_home: 'Home',
    nav_menu: 'Menu',
    nav_about: 'About',
    nav_reviews: 'Reviews',
    nav_contact: 'Contact',
    nav_reserve: 'Reserve a Table',
    nav_dashboard: 'Dashboard',

    // Hero
    hero_badge: '✦ Est. 2015 · Milano, Italy',
    hero_title1: 'Where Every Dish',
    hero_title2: 'Tells a Story',
    hero_subtitle: 'Indulge in the art of fine dining. Crafted with passion, served with elegance — an experience for all the senses.',
    hero_reserve: 'Reserve a Table',
    hero_menu: 'Explore Menu',
    hero_stat1_num: '12+',
    hero_stat1_label: 'Years of Excellence',
    hero_stat2_num: '48',
    hero_stat2_label: 'Signature Dishes',
    hero_stat3_num: '2',
    hero_stat3_label: 'Michelin Stars',

    // Menu
    menu_label: 'Our Menu',
    menu_title: 'Culinary Masterpieces',
    menu_desc: 'Every dish is a canvas where tradition meets innovation, crafted from the finest seasonal ingredients.',
    menu_cat_all: 'All',
    menu_cat_starters: 'Starters',
    menu_cat_main: 'Main Course',
    menu_cat_desserts: 'Desserts',
    menu_view_full: 'View Full Menu',
    menu_order: 'Order Now →',
    modal_reserve: 'Book a Table →',

    // About
    about_label: 'Our Story',
    about_title1: 'A Passion for',
    about_title2: 'Exceptional Cuisine',
    about_p1: 'Founded in 2015 by Chef Marco Rossi, Bella Vista was born from a dream — to create a place where extraordinary food meets warm hospitality. Nestled in the heart of the city, our restaurant blends Italian tradition with modern culinary techniques.',
    about_p2: 'Every dish reflects our unwavering commitment to quality. We partner with local farmers and artisan producers to bring you the freshest ingredients, transformed into culinary masterpieces by our passionate team.',
    about_years: 'Years of Culinary Excellence',
    about_f1_title: 'Farm to Table',
    about_f1_desc: 'Fresh ingredients sourced daily from local farms and trusted suppliers.',
    about_f2_title: 'Master Chefs',
    about_f2_desc: 'Award-winning culinary team with decades of international experience.',
    about_f3_title: 'Premium Wine',
    about_f3_desc: 'An extensive selection of over 200 fine wines from around the world.',
    about_f4_title: 'Private Events',
    about_f4_desc: 'Bespoke dining experiences for weddings, anniversaries, and corporate events.',

    // Testimonials
    test_label: 'Testimonials',
    test_title: 'What Our Guests Say',

    // Reservation
    res_label: 'Book a Table',
    res_title1: 'Reserve Your',
    res_title2: 'Experience',
    res_desc: 'Join us for an unforgettable evening. We welcome reservations for all occasions — from intimate dinners to large celebrations.',
    res_hours_title: 'Opening Hours',
    res_hours1: 'Mon–Thu: 12pm – 10pm',
    res_hours2: 'Fri–Sun: 12pm – 11:30pm',
    res_location_title: 'Location',
    res_phone_title: 'Reservations',
    res_field_name: 'Full Name',
    res_field_email: 'Email',
    res_field_date: 'Date',
    res_field_time: 'Time',
    res_field_phone: 'Phone',
    res_field_guests: 'Guests',
    res_field_message: 'Special Requests',
    res_placeholder_name: 'Your name',
    res_placeholder_email: 'your@email.com',
    res_placeholder_phone: '+1 234 567 890',
    res_placeholder_message: 'Any dietary requirements, allergies, or special occasions...',
    res_select_time: 'Select time',
    res_person: 'Person',
    res_people: 'People',
    res_submit: 'Confirm Reservation',
    res_success_title: 'Reservation Confirmed!',
    res_success_text: 'Thank you',
    res_success_text2: 'We look forward to welcoming you on',
    res_success_at: 'at',
    res_another: 'Make Another Reservation',

    // Footer
    footer_tagline: 'Where every moment becomes a cherished memory. Experience the finest Italian cuisine in an unforgettable setting.',
    footer_links: 'Quick Links',
    footer_contact: 'Contact',
    footer_newsletter: 'Newsletter',
    footer_newsletter_desc: 'Get exclusive offers and seasonal menu updates.',
    footer_copy: '© 2026 Bella Vista Fine Dining. All rights reserved.',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
  },

  ru: {
    nav_home: 'Главная',
    nav_menu: 'Меню',
    nav_about: 'О нас',
    nav_reviews: 'Отзывы',
    nav_contact: 'Контакты',
    nav_reserve: 'Забронировать стол',
    nav_dashboard: 'Панель',

    hero_badge: '✦ Осн. 2015 · Милан, Италия',
    hero_title1: 'Где каждое блюдо',
    hero_title2: 'Рассказывает историю',
    hero_subtitle: 'Погрузитесь в искусство изысканной кухни. Создано с любовью, подано с элегантностью — опыт для всех чувств.',
    hero_reserve: 'Забронировать стол',
    hero_menu: 'Изучить меню',
    hero_stat1_num: '12+',
    hero_stat1_label: 'Лет совершенства',
    hero_stat2_num: '48',
    hero_stat2_label: 'Фирменных блюд',
    hero_stat3_num: '2',
    hero_stat3_label: 'Звезды Мишлен',

    menu_label: 'Наше меню',
    menu_title: 'Кулинарные шедевры',
    menu_desc: 'Каждое блюдо — это холст, где традиции встречаются с инновациями, из лучших сезонных ингредиентов.',
    menu_cat_all: 'Все',
    menu_cat_starters: 'Закуски',
    menu_cat_main: 'Основные блюда',
    menu_cat_desserts: 'Десерты',
    menu_view_full: 'Полное меню',
    menu_order: 'Заказать →',
    modal_reserve: 'Забронировать стол →',

    about_label: 'Наша история',
    about_title1: 'Страсть к',
    about_title2: 'Исключительной кухне',
    about_p1: 'Основанный в 2015 году шеф-поваром Марко Росси, Bella Vista родился из мечты — создать место, где необыкновенная еда встречается с теплым гостеприимством. Расположенный в сердце города, наш ресторан сочетает итальянские традиции с современными кулинарными техниками.',
    about_p2: 'Каждое блюдо отражает нашу непоколебимую приверженность качеству. Мы сотрудничаем с местными фермерами и производителями, чтобы предложить вам самые свежие ингредиенты.',
    about_years: 'Лет кулинарного совершенства',
    about_f1_title: 'С фермы на стол',
    about_f1_desc: 'Свежие ингредиенты ежедневно с местных ферм и проверенных поставщиков.',
    about_f2_title: 'Мастера-шеф-повара',
    about_f2_desc: 'Отмеченная наградами кулинарная команда с десятилетиями международного опыта.',
    about_f3_title: 'Премиальные вина',
    about_f3_desc: 'Обширная коллекция из более 200 изысканных вин со всего мира.',
    about_f4_title: 'Частные мероприятия',
    about_f4_desc: 'Индивидуальный обеденный опыт для свадеб, юбилеев и корпоративных мероприятий.',

    test_label: 'Отзывы',
    test_title: 'Что говорят наши гости',

    res_label: 'Забронировать стол',
    res_title1: 'Забронируйте',
    res_title2: 'Ваш опыт',
    res_desc: 'Присоединяйтесь к нам для незабываемого вечера. Мы принимаем бронирования для любых случаев.',
    res_hours_title: 'Часы работы',
    res_hours1: 'Пн–Чт: 12:00 – 22:00',
    res_hours2: 'Пт–Вс: 12:00 – 23:30',
    res_location_title: 'Расположение',
    res_phone_title: 'Бронирование',
    res_field_name: 'Полное имя',
    res_field_email: 'Email',
    res_field_date: 'Дата',
    res_field_time: 'Время',
    res_field_phone: 'Телефон',
    res_field_guests: 'Гости',
    res_field_message: 'Особые пожелания',
    res_placeholder_name: 'Ваше имя',
    res_placeholder_email: 'ваш@email.com',
    res_placeholder_phone: '+7 999 123 45 67',
    res_placeholder_message: 'Диетические требования, аллергии или особые случаи...',
    res_select_time: 'Выберите время',
    res_person: 'Человек',
    res_people: 'Человека',
    res_submit: 'Подтвердить бронирование',
    res_success_title: 'Бронирование подтверждено!',
    res_success_text: 'Спасибо',
    res_success_text2: 'Мы с нетерпением ждём вас',
    res_success_at: 'в',
    res_another: 'Новое бронирование',

    footer_tagline: 'Где каждый момент становится драгоценным воспоминанием. Лучшая итальянская кухня в незабываемой обстановке.',
    footer_links: 'Быстрые ссылки',
    footer_contact: 'Контакты',
    footer_newsletter: 'Рассылка',
    footer_newsletter_desc: 'Эксклюзивные предложения и обновления сезонного меню.',
    footer_copy: '© 2026 Bella Vista Fine Dining. Все права защищены.',
    footer_privacy: 'Политика конфиденциальности',
    footer_terms: 'Условия использования',
  },

  uz: {
    nav_home: 'Bosh sahifa',
    nav_menu: 'Menyu',
    nav_about: 'Biz haqimizda',
    nav_reviews: 'Sharhlar',
    nav_contact: 'Aloqa',
    nav_reserve: 'Stol band qilish',
    nav_dashboard: 'Boshqaruv',

    hero_badge: '✦ Tash. 2015 · Milano, Italiya',
    hero_title1: "Har bir taom",
    hero_title2: 'O\'z hikoyasini aytadi',
    hero_subtitle: 'Nozik oshxona san\'atiga sho\'ng\'ing. Ishtiyoq bilan yaratilgan, nafis taqdim etilgan — barcha his-tuyg\'ular uchun tajriba.',
    hero_reserve: 'Stol band qilish',
    hero_menu: 'Menyuni ko\'rish',
    hero_stat1_num: '12+',
    hero_stat1_label: 'Yillik tajriba',
    hero_stat2_num: '48',
    hero_stat2_label: 'Imzoli taomlar',
    hero_stat3_num: '2',
    hero_stat3_label: 'Mishlen yulduzi',

    menu_label: 'Bizning menyu',
    menu_title: 'Oshpazlik shoheasarlari',
    menu_desc: 'Har bir taom — an\'ana va innovatsiya uchrashadigan maydonda, eng yaxshi mavsumiy mahsulotlardan tayyorlanadi.',
    menu_cat_all: 'Barchasi',
    menu_cat_starters: 'Murakkab',
    menu_cat_main: 'Asosiy taomlar',
    menu_cat_desserts: 'Desertlar',
    menu_view_full: 'To\'liq menyu',
    menu_order: 'Buyurtma berish →',
    modal_reserve: 'Stol band qilish →',

    about_label: 'Bizning hikoya',
    about_title1: 'Ajoyib oshxonaga',
    about_title2: 'Bo\'lgan ishtiyoq',
    about_p1: '2015 yilda shef-oshpaz Marko Rossi tomonidan asos solingan Bella Vista orzudan tug\'ildi — oddiy ovqat va iliq mehmondo\'stlik uchrashadigan joy yaratish. Shahar markazida joylashgan restoranımız italyan an\'analarini zamonaviy oshpazlik texnikasi bilan birlashtiradi.',
    about_p2: 'Har bir taom sifatga bo\'lgan qat\'iy sadoqatimizni aks ettiradi. Eng yangi mahsulotlarni taqdim etish uchun mahalliy fermerlar va hunarmand ishlab chiqaruvchilar bilan hamkorlik qilamiz.',
    about_years: 'Yillik oshpazlik mahorati',
    about_f1_title: 'Fermadan dasturxonga',
    about_f1_desc: 'Mahalliy fermalar va ishonchli yetkazib beruvchilardan har kuni yangi mahsulotlar.',
    about_f2_title: 'Usta oshpazlar',
    about_f2_desc: 'O\'nlab yillik xalqaro tajribaga ega mukofotlangan oshpazlik jamoasi.',
    about_f3_title: 'Premium sharob',
    about_f3_desc: 'Dunyo bo\'ylab 200 dan ortiq noyob sharoblar keng tanlovda.',
    about_f4_title: 'Xususiy tadbirlar',
    about_f4_desc: 'To\'ylar, yubileylar va korporativ tadbirlar uchun maxsus ovqatlanish tajribasi.',

    test_label: 'Sharhlar',
    test_title: 'Mehmonlarimiz nima deydi',

    res_label: 'Stol band qilish',
    res_title1: 'Tajribangizni',
    res_title2: 'Band qiling',
    res_desc: 'Unutilmas kechqurun uchun bizga qo\'shiling. Uyushgan kechki ovqatdan tortib katta bayramlargacha har qanday tadbir uchun.',
    res_hours_title: 'Ish vaqti',
    res_hours1: 'Du–Pa: 12:00 – 22:00',
    res_hours2: 'Ju–Ya: 12:00 – 23:30',
    res_location_title: 'Manzil',
    res_phone_title: 'Bron qilish',
    res_field_name: 'To\'liq ism',
    res_field_email: 'Elektron pochta',
    res_field_date: 'Sana',
    res_field_time: 'Vaqt',
    res_field_phone: 'Telefon',
    res_field_guests: 'Mehmonlar',
    res_field_message: 'Maxsus talablar',
    res_placeholder_name: 'Ismingiz',
    res_placeholder_email: 'sizning@email.com',
    res_placeholder_phone: '+998 90 123 45 67',
    res_placeholder_message: 'Parhez talablari, allergiyalar yoki maxsus tadbirlar...',
    res_select_time: 'Vaqtni tanlang',
    res_person: 'Kishi',
    res_people: 'Kishi',
    res_submit: 'Bronni tasdiqlash',
    res_success_title: 'Bron tasdiqlandi!',
    res_success_text: 'Rahmat',
    res_success_text2: 'Sizni kutib olishdan xursandmiz',
    res_success_at: 'soatida',
    res_another: 'Yangi bron qilish',

    footer_tagline: 'Har bir lahza aziz xotiraga aylanadi. Unutilmas muhitda eng yaxshi italyan taomlari.',
    footer_links: 'Tezkor havolalar',
    footer_contact: 'Aloqa',
    footer_newsletter: 'Xabarnoma',
    footer_newsletter_desc: 'Eksklyuziv takliflar va mavsumiy menyu yangilanishlarini oling.',
    footer_copy: '© 2026 Bella Vista Fine Dining. Barcha huquqlar himoyalangan.',
    footer_privacy: 'Maxfiylik siyosati',
    footer_terms: 'Foydalanish shartlari',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('uz');
  const t = (key) => translations[lang][key] || translations['en'][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
